// <auto-generated />
using Backend.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914080835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Api.Domain.Entities.TransfusionCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("adresa");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nume");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("oras");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("program");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefon");

                    b.HasKey("Id")
                        .HasName("pk_transfusion_centers");

                    b.ToTable("transfusion_centers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Str. Academiei 11, Chișinău",
                            Lat = 47.015900000000002,
                            Lng = 28.841899999999999,
                            Nume = "Centrul Național de Transfuzie a Sângelui",
                            Oras = "Chișinău",
                            Program = "Luni–Vineri, 08:00–15:00",
                            Telefon = "+373 22 727 511"
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Str. Decebal 113, Bălți",
                            Lat = 47.756100000000004,
                            Lng = 27.9298,
                            Nume = "Centrul Național de Transfuzie a Sângelui — filiala Bălți",
                            Oras = "Bălți",
                            Program = "Luni–Vineri, 08:00–14:00",
                            Telefon = "+373 231 22 555"
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "IMSP Spitalul Raional Cahul",
                            Lat = 45.907499999999999,
                            Lng = 28.1936,
                            Nume = "Cabinet de Transfuzie a Sângelui — Spitalul Raional Cahul",
                            Oras = "Cahul",
                            Program = "Luni–Vineri, 08:00–14:00",
                            Telefon = "+373 299 22 555"
                        },
                        new
                        {
                            Id = 4,
                            Adresa = "IMSP Spitalul Raional Soroca",
                            Lat = 48.156700000000001,
                            Lng = 28.293900000000001,
                            Nume = "Cabinet de Transfuzie a Sângelui — Spitalul Raional Soroca \"A. Prisăcari\"",
                            Oras = "Soroca",
                            Program = "Luni–Vineri, 08:00–14:00",
                            Telefon = "+373 230 22 555"
                        },
                        new
                        {
                            Id = 5,
                            Adresa = "Str. Odesscaia 2, Comrat",
                            Lat = 46.302100000000003,
                            Lng = 28.656700000000001,
                            Nume = "Cabinet de Transfuzie a Sângelui — Spitalul Raional Comrat \"Isaac Gurfinchel\"",
                            Oras = "Comrat",
                            Program = "Luni–Vineri, 08:00–14:00",
                            Telefon = "+373 298 22 555"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
